# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master


jobs:


- job: Docs
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - script: conda env create --quiet --file ci/doc.yml
    displayName: Create Anaconda environment
  - script: |
      source activate test_env
      # Replicate the exact environment created by the readthedocs CI
      conda install --yes --quiet -c pkgs/main mock pillow sphinx sphinx_rtd_theme
    displayName: Replicate readthedocs CI environment
  - script: |
      source activate test_env
      cd doc/sphinx/
      sphinx-build -W --keep-going -j auto -b html -d _build/doctrees source build
    displayName: Build HTML docs
