codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: 100%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    project:
      default: false
      library:
        target: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
        paths:
          - "pvlib/.*"
      tests:
        target: 95%
        paths:
          - "pvlib/tests/.*"

comment: off

# "flags" are used to identify subsets of the overall codebase when calculating coverage.
# Currently used for "iotools" (just pvlib.iotools) and "core" (everything else)
# https://docs.codecov.com/docs/flags#recommended-automatic-flag-management
flag_management:
  default_rules:
