name: pvlib
channels:
    - defaults
    - http://conda.anaconda.org/Unidata
dependencies:
    - python=2.7 
    - numpy
    - scipy
    - pandas
    - pytz
    - ephem
    - numba
    - ipython
    - sphinx
    - numpydoc
    - matplotlib
    - seaborn
    - siphon