name: pvlibdocs
channels:
    - conda-forge
    - defaults
dependencies:
    - coveralls
    - cython
    - ephem
    - ipython
    - matplotlib
    - netcdf4
    - nose
    - numba
    - numpy
    - pandas
    - pip
    - pytables  # tables when using pip+PyPI
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-timeout
    - python=3.6
    - pytz
    - requests
    - scipy
    - shapely  # pvfactors dependency
    - siphon  # conda-forge
    - sphinx
    - sphinx_rtd_theme
    - pip:
        - pvfactors==1.0.1
