name: pvlibdocs
channels:
    - conda-forge
    - defaults
dependencies:
    - python=2.7
    - mock  # needed for local python 2.7 builds
    - numpy
    - scipy
    - pandas
    - pytz
    - ephem
    - numba
    - ipython=4.0.1
    - ipywidgets
    - numpydoc
    - matplotlib
    - seaborn
    - siphon
    - sphinx=1.4.8
    - netCDF4=1.2.4
    - hdf4=4.2.12
    - sphinx_rtd_theme
    - docutils
