name: Python Flake8 Linter
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Flake8 linter
        run: pip install flake8
      - name: Setup Flake8 output matcher for PR annotations
        run: echo '::add-matcher::.github/workflows/flake8-pr-annotation-matcher.json'
      - name: Run Flake8 linter
        run: flake8
               --exclude pvlib/version.py
               --ignore E201,E241,E226,W503,W504
               --max-line-length 79
               .
